version: '3'
services:
  node:
    build: 
      dockerfile: ./Dockerfile
    container_name: talker_manager_api
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db
    env_file:
      - .env

  db:
    container_name: talker_manager_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password